language: ruby
rvm:
  - 2.3.0
services:
  - postgres

addons:
  postgresql: '9.4'
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - bundle exec rake
cache:
  directories:
  - vendor/bundle
